# CodeRabbit configuration file for Repomix project
# See: https://docs.coderabbit.ai/getting-started/configure-coderabbit/

# Language configuration
language: en-US

# Review configuration
reviews:
  # Review levels for different types of changes
  profile: chill # Options: chill, assertive

  # Auto review only on PR creation, not on subsequent changes
  auto_review:
    enabled: true
    drafts: false

    # Disable incremental reviews after PR creation
    auto_incremental_review: false

  # Request changes for critical issues
  request_changes_workflow: true

  # High-level summary for complex PRs
  high_level_summary: false

  # Poem style for fun summary (optional)
  poem: false

# Chat configuration
chat:
  auto_reply: false

# Knowledge base configuration
knowledge_base:
  # Opt out of sensitive file content analysis
  opt_out: false

# Early access features
early_access: true
